services:
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --quiet --logpath /dev/null 2>&1
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  api:
    container_name: api
    build:
      context: ./backend
      target: ${NODE_ENV}
    user: ${UID}:${GID}
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV
      - SERVER_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - JWT_SECRET_DEV
      - JWT_SECRET_PROD
    depends_on:
      - mongo

  client:
    container_name: client
    build:
      context: ./frontend
      target: ${NODE_ENV}
    restart: always
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - CLIENT_PORT
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data:
    driver: local
